name: Build all images

on:
  push:
    branches: [ "**" ]  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build all docker images
      run: docker-compose build
